# This workflow will install the dependencies and then build and deploy the
# TypeScript documentation website to the docs branch.

name: Publish Documentation

on:
  push:
    tags:
      - '*'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Typedoc to GitHub Pages
        uses: product-os/typedoc-publish-action@v1
